---
- name: Install Nginx
  hosts: web
  become: yes
  vars:
    nginx_listen_port: 8080

  tasks:
    - name: update apt
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: latest
      notify:
        - restart nginx
    
    - name: NGINX | Create NGINX config file from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: 
        - reload nginx
      tags:
        - nginx-configuration

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

